### ISSUE TITLE
which urdf ?

### ISSUE THREAD

**Issue by luoww1992** [prashanthr05/gazebo_example_plugins#2]
i don't know the .urdf file name in this link:
https://www.researchgate.net/publication/361182086_State_Estimation_for_Human_Motion_and_Humanoid_Locomotion

![urdf](https://github.com/prashanthr05/gazebo_example_plugins/assets/45957595/b97d7c35-5dad-49f3-9cdd-0ded65a7a384)

can  you share me this urdf file ?
thank you !

**Comment by traversaro** [comment]
I guess it is a URDF file from https://github.com/robotology/human-gazebo, fyi @CarlottaSartore @lrapetti .

**Comment by lrapetti** [comment]
> I guess it is a URDF file from https://github.com/robotology/human-gazebo, fyi @CarlottaSartore @lrapetti .

Yess, you can find the model https://github.com/robotology/human-gazebo.

If instead, you need to generate a model for a specific subject you can have a look at https://github.com/ami-iit/human-model-generator.

**Comment by prashanthr05** [comment]
Just noticed this issue. 
@traversaro  @lrapetti Thank you for your quick response, guys :)

Closing.
